name: Notify Discord on Pull Request Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - DEV
      - discord-webhook
  workflow_dispatch: # For manual runs

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history so we can access commits

      - name: Get pull request details
        if: github.event_name == 'pull_request'
        id: pr
        run: |
          echo "source_branch=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          echo "target_branch=$(jq -r '.pull_request.base.ref' "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
          commits=$(gh pr view ${{ github.event.pull_request.number }} --json commits --jq '.commits[].oid')
          commit_messages=$(gh pr view ${{ github.event.pull_request.number }} --json commits --jq '.commits[].messageHeadline')
          gh pr view ${{ github.event.pull_request.number }} --json commits
          echo "commits=$(echo $commits | xargs -n1 | awk '{print substr($1,1,7)}')" >> $GITHUB_ENV
          echo "commit_messages=$(echo $commit_messages | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_ENV

      - name: Set test data (for manual run)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "source_branch=test-source-branch" >> $GITHUB_ENV
          echo "target_branch=test-target-branch" >> $GITHUB_ENV
          echo "commits=test123,test456" >> $GITHUB_ENV
          echo "commit_messages='Test commit message 1, Test commit message 2'" >> $GITHUB_ENV

      - name: Construct JSON payload
        id: payload
        run: |
          description=$(paste -d " " <(echo $commits | tr ',' '\n') <(echo $commit_messages | tr ',' '\n'))
          jq -n --arg username "Github changes (backend)" \
              --arg title "$source_branch merged into $target_branch" \
              --arg description "$description" \
              --arg thumbnail_url "https://scontent-arn2-1.xx.fbcdn.net/v/t39.30808-6/309442137_496211302516262_905279675209114671_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=gTytY4lsV2kQ7kNvgHUXTQd&_nc_ht=scontent-arn2-1.xx&_nc_gid=A--MMk5IUx7Ql6LlT_eJRJp&oh=00_AYBJu2cx1DC67P2QIQaCgoaPv9LaGcV9du3ckKLcUGaRCA&oe=670AB4D5" \
              --arg footer_text "footer for scale" \
              '{
                  "username": $username,
                  "embeds": [
                      {
                      "title": $title,
                      "color": 102204,
                      "description": $description,
                      "thumbnail": {"url": $thumbnail_url},
                      "footer": {"text": $footer_text}
                      }
                  ]
                  }' > payload.json

      - name: Send to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          cat payload.json # This will show the JSON for debugging
          curl -X POST -H "Content-Type: application/json" -d @payload.json "$WEBHOOK_URL"
